python scripts/train_poisoned_visualglm_classifier.py \
  --config configs/visualglm_defense.yaml \
  --train-dir /home/dengxuan/DATA/imagenet1k/train \
  --val-dir /home/dengxuan/DATA/imagenet1k/val \
  --device cuda:1 \
  --epochs 1 \
  --batch-size 16 \
  --num-workers 8 \
  --lr-head 1e-4 \
  --num-classes 1000 \
  --image-size 224 \
  --normalize-for-model \
  --attack-type blended \
  --label-consistent \
  --blend-alpha 0.2 \
  --poison-ratio 0.1 \
  --target-id 239 \
  --init-classifier-head-path checkpoints/classifier_head.pt \
  --save-dir checkpoints \
  --save-prefix imagenet_blended_lc_t239